### ISSUE TITLE
Elixir 1.15 incompatible?

### ISSUE THREAD

**Issue by ViseLuca** [PSPDFKit-labs/bypass#135]
Hi,
In my repository after an upgrade to Elixir 1.15 seems that something is not fully compatible and some tests are breaking.

```
 ** (RuntimeError) route error
             (bypass 2.1.0) lib/bypass/plug.ex:28: Bypass.Plug.call/2
             (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
             (cowboy 2.10.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
             (cowboy 2.10.0) /app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
             (cowboy 2.10.0) /app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
             (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3 2023-06-30T12:11:46.405000Z 
```

Meanwhile until Elixir 1.14.5 everything was working well. Any idea?

**Comment by hissssst** [comment]
I get this exception from time to time even on 1.14.5 too
